export const GET_GAMES = 'GET_GAMES';
export const GET_GAMES_SUCCESS = 'GET_GAMES_SUCCESS';
export const GET_GAMES_FAILURE = 'GET_GAMES_FAILURE';

export const SET_SEARCH_BAR = 'SET_SEARCH_BAR';

export const SHOW_SELECTED_GAME = 'SHOW_SELECTED_GAME';
