export const GET_GAMES = 'GET_GAMES';
export const GET_GAMES_SUCCESS = 'GET_GAMES_SUCCESS';
export const GET_GAMES_FAILURE = 'GET_GAMES_FAILURE';

export const SET_SEARCH_BAR = 'SET_SEARCH_BAR';
export const SHOW_SELECTED_GAME = 'SHOW_SELECTED_GAME';

export const DELETE_GAME = 'DELETE_GAME';
export const DELETE_GAME_SUCCESS = 'DELETE_GAME_SUCCESS';
export const DELETE_GAME_FAILURE = 'DELETE_GAME_FAILURE';

export const POST_GAME = 'POST_GAME';
export const POST_GAME_SUCCESS = 'POST_GAME_SUCCESS';
export const POST_GAME_FAILURE = 'POST_GAME_FAILURE';
